// <auto-generated />
using System;
using Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251204083556_AddAracModelOptions")]
    partial class AddAracModelOptions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Api.Models.AracModelBilgileri", b =>
                {
                    b.Property<int>("ModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ModelID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModelId"));

                    b.Property<decimal>("GunlukFiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Marka")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ResimUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Segment")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VitesTipi")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("YakitTipi")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Yil")
                        .HasColumnType("int");

                    b.HasKey("ModelId")
                        .HasName("PK__AracMode__E8D7A1CCA8CDFAD9");

                    b.ToTable("AracModelBilgileri", "FILO");
                });

            modelBuilder.Entity("Api.Models.Araclar", b =>
                {
                    b.Property<int>("AracId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AracID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AracId"));

                    b.Property<DateTime?>("AlisTarihi")
                        .HasColumnType("datetime");

                    b.Property<string>("Durum")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("GuncelSubeId")
                        .HasColumnType("int")
                        .HasColumnName("GuncelSubeID");

                    b.Property<int?>("Km")
                        .HasColumnType("int");

                    b.Property<int>("ModelId")
                        .HasColumnType("int")
                        .HasColumnName("ModelID");

                    b.Property<string>("Plaka")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Renk")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SasiNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AracId")
                        .HasName("PK__Araclar__1E09A830056413DC");

                    b.HasIndex("GuncelSubeId");

                    b.HasIndex("ModelId");

                    b.ToTable("Araclar", "FILO");
                });

            modelBuilder.Entity("Api.Models.Bakimlar", b =>
                {
                    b.Property<int>("BakimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BakimID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BakimId"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("AracId")
                        .HasColumnType("int")
                        .HasColumnName("AracID");

                    b.Property<DateTime>("BakimTarihi")
                        .HasColumnType("datetime");

                    b.Property<string>("BakimTipi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Tutar")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("BakimId")
                        .HasName("PK__Bakimlar__7227287E783F25C5");

                    b.HasIndex("AracId");

                    b.ToTable("Bakimlar", "FILO");
                });

            modelBuilder.Entity("Api.Models.Faturalar", b =>
                {
                    b.Property<int>("FaturaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FaturaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FaturaId"));

                    b.Property<DateTime>("FaturaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("KiralamaId")
                        .HasColumnType("int")
                        .HasColumnName("KiralamaID");

                    b.Property<decimal?>("Tutar")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("FaturaId")
                        .HasName("PK__Faturala__84301C40994C9B46");

                    b.HasIndex("KiralamaId");

                    b.ToTable("Faturalar", "OPERASYON");
                });

            modelBuilder.Entity("Api.Models.Kiralamalar", b =>
                {
                    b.Property<int>("KiralamaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("KiralamaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KiralamaId"));

                    b.Property<int>("AlisSubeId")
                        .HasColumnType("int")
                        .HasColumnName("AlisSubeID");

                    b.Property<DateTime?>("AlisTarihi")
                        .HasColumnType("datetime");

                    b.Property<int>("AracId")
                        .HasColumnType("int")
                        .HasColumnName("AracID");

                    b.Property<string>("Durum")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("GercekTeslimTarihi")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("GunlukUcret")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("MusteriId")
                        .HasColumnType("int")
                        .HasColumnName("MusteriID");

                    b.Property<DateTime?>("TahminiTeslimTarihi")
                        .HasColumnType("datetime");

                    b.Property<int>("TeslimSubeId")
                        .HasColumnType("int")
                        .HasColumnName("TeslimSubeID");

                    b.HasKey("KiralamaId")
                        .HasName("PK__Kiralama__5EFEA0B8A87CBBE8");

                    b.HasIndex("AlisSubeId");

                    b.HasIndex("AracId");

                    b.HasIndex("MusteriId");

                    b.HasIndex("TeslimSubeId");

                    b.ToTable("Kiralamalar", "OPERASYON");
                });

            modelBuilder.Entity("Api.Models.Kullanicilar", b =>
                {
                    b.Property<int>("KullaniciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("KullaniciID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KullaniciId"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("KullaniciId")
                        .HasName("PK__Kullanic__E011F09B32916840");

                    b.ToTable("Kullanicilar", "OPERASYON");
                });

            modelBuilder.Entity("Api.Models.Musteriler", b =>
                {
                    b.Property<int>("MusteriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MusteriID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MusteriId"));

                    b.Property<string>("AdSoyad")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Adres")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EhliyetNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("EhliyetTarihi")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TcNo")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Telefon")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MusteriId")
                        .HasName("PK__Musteril__72624471ECBE379A");

                    b.ToTable("Musteriler", "OPERASYON");
                });

            modelBuilder.Entity("Api.Models.Rezervasyonlar", b =>
                {
                    b.Property<int>("RezervasyonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RezervasyonID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RezervasyonId"));

                    b.Property<int>("AlisSubeId")
                        .HasColumnType("int")
                        .HasColumnName("AlisSubeID");

                    b.Property<int?>("AracId")
                        .HasColumnType("int")
                        .HasColumnName("AracID");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("MusteriId")
                        .HasColumnType("int")
                        .HasColumnName("MusteriID");

                    b.Property<string>("Notlar")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("PlanlananAlisTarihi")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("PlanlananTeslimTarihi")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("RezervasyonTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("TahminiUcret")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("TeslimSubeId")
                        .HasColumnType("int")
                        .HasColumnName("TeslimSubeID");

                    b.HasKey("RezervasyonId")
                        .HasName("PK__Rezervas__CD4DF978B1793651");

                    b.HasIndex("AlisSubeId");

                    b.HasIndex("AracId");

                    b.HasIndex("MusteriId");

                    b.HasIndex("TeslimSubeId");

                    b.ToTable("Rezervasyonlar", "OPERASYON");
                });

            modelBuilder.Entity("Api.Models.Subeler", b =>
                {
                    b.Property<int>("SubeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SubeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubeId"));

                    b.Property<string>("Adres")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Il")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ilce")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SubeAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SubeId")
                        .HasName("PK__Subeler__C3041019D966155F");

                    b.ToTable("Subeler", "OPERASYON");
                });

            modelBuilder.Entity("Api.Models.Araclar", b =>
                {
                    b.HasOne("Api.Models.Subeler", "GuncelSube")
                        .WithMany("Araclars")
                        .HasForeignKey("GuncelSubeId")
                        .HasConstraintName("FK__Araclar__GuncelS__3C69FB99");

                    b.HasOne("Api.Models.AracModelBilgileri", "Model")
                        .WithMany("Araclars")
                        .HasForeignKey("ModelId")
                        .IsRequired()
                        .HasConstraintName("FK__Araclar__ModelID__3B75D760");

                    b.Navigation("GuncelSube");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("Api.Models.Bakimlar", b =>
                {
                    b.HasOne("Api.Models.Araclar", "Arac")
                        .WithMany("Bakimlars")
                        .HasForeignKey("AracId")
                        .IsRequired()
                        .HasConstraintName("FK__Bakimlar__AracID__3F466844");

                    b.Navigation("Arac");
                });

            modelBuilder.Entity("Api.Models.Faturalar", b =>
                {
                    b.HasOne("Api.Models.Kiralamalar", "Kiralama")
                        .WithMany("Faturalars")
                        .HasForeignKey("KiralamaId")
                        .IsRequired()
                        .HasConstraintName("FK__Faturalar__Kiral__534D60F1");

                    b.Navigation("Kiralama");
                });

            modelBuilder.Entity("Api.Models.Kiralamalar", b =>
                {
                    b.HasOne("Api.Models.Subeler", "AlisSube")
                        .WithMany("KiralamalarAlisSubes")
                        .HasForeignKey("AlisSubeId")
                        .IsRequired()
                        .HasConstraintName("FK__Kiralamal__AlisS__4E88ABD4");

                    b.HasOne("Api.Models.Araclar", "Arac")
                        .WithMany("Kiralamalars")
                        .HasForeignKey("AracId")
                        .IsRequired()
                        .HasConstraintName("FK__Kiralamal__AracI__4D94879B");

                    b.HasOne("Api.Models.Musteriler", "Musteri")
                        .WithMany("Kiralamalars")
                        .HasForeignKey("MusteriId")
                        .IsRequired()
                        .HasConstraintName("FK__Kiralamal__Muste__4CA06362");

                    b.HasOne("Api.Models.Subeler", "TeslimSube")
                        .WithMany("KiralamalarTeslimSubes")
                        .HasForeignKey("TeslimSubeId")
                        .IsRequired()
                        .HasConstraintName("FK__Kiralamal__Tesli__4F7CD00D");

                    b.Navigation("AlisSube");

                    b.Navigation("Arac");

                    b.Navigation("Musteri");

                    b.Navigation("TeslimSube");
                });

            modelBuilder.Entity("Api.Models.Rezervasyonlar", b =>
                {
                    b.HasOne("Api.Models.Subeler", "AlisSube")
                        .WithMany("RezervasyonlarAlisSubes")
                        .HasForeignKey("AlisSubeId")
                        .IsRequired()
                        .HasConstraintName("FK__Rezervasy__AlisS__48CFD27E");

                    b.HasOne("Api.Models.Araclar", "Arac")
                        .WithMany("Rezervasyonlars")
                        .HasForeignKey("AracId")
                        .HasConstraintName("FK__Rezervasy__AracI__47DBAE45");

                    b.HasOne("Api.Models.Musteriler", "Musteri")
                        .WithMany("Rezervasyonlars")
                        .HasForeignKey("MusteriId")
                        .IsRequired()
                        .HasConstraintName("FK__Rezervasy__Muste__46E78A0C");

                    b.HasOne("Api.Models.Subeler", "TeslimSube")
                        .WithMany("RezervasyonlarTeslimSubes")
                        .HasForeignKey("TeslimSubeId")
                        .IsRequired()
                        .HasConstraintName("FK__Rezervasy__Tesli__49C3F6B7");

                    b.Navigation("AlisSube");

                    b.Navigation("Arac");

                    b.Navigation("Musteri");

                    b.Navigation("TeslimSube");
                });

            modelBuilder.Entity("Api.Models.AracModelBilgileri", b =>
                {
                    b.Navigation("Araclars");
                });

            modelBuilder.Entity("Api.Models.Araclar", b =>
                {
                    b.Navigation("Bakimlars");

                    b.Navigation("Kiralamalars");

                    b.Navigation("Rezervasyonlars");
                });

            modelBuilder.Entity("Api.Models.Kiralamalar", b =>
                {
                    b.Navigation("Faturalars");
                });

            modelBuilder.Entity("Api.Models.Musteriler", b =>
                {
                    b.Navigation("Kiralamalars");

                    b.Navigation("Rezervasyonlars");
                });

            modelBuilder.Entity("Api.Models.Subeler", b =>
                {
                    b.Navigation("Araclars");

                    b.Navigation("KiralamalarAlisSubes");

                    b.Navigation("KiralamalarTeslimSubes");

                    b.Navigation("RezervasyonlarAlisSubes");

                    b.Navigation("RezervasyonlarTeslimSubes");
                });
#pragma warning restore 612, 618
        }
    }
}
